
loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
minio:
  enabled: true
test:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
